#!/bin/sh
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "🚫 [安全護欄] 為了保護專案，禁止直接 Push 到 main 或 master 分支！"
  echo "👉 請建立新的分支，並透過 GitHub 建立 Pull Request (PR) 進行合併。"
  exit 1
fi
